/**
 * @abstract Single file to manage functions that build any and all payloads to the OpenAI API.
 * Imported altogether inside main function file as "Prompts" to be able to use dot
 * notation to invoke to keep it human readable.
 */

/**
 * @param {string} algoName name of the algorithm for which to generate a toy problem
 * @param {string} model which chat gpt model to use
 *
 * @returns {object} payload for OpenAI API call
 */
export const getToyProblem = (algoName, model) => {
  return {
    "model": model,
    "messages": [
      {
        "role": "system",
        "content": "You are a professional software engineer adept at creating algorithmic problems."
      },
      {
        "role": "user",
        "content": `Please create a coding toy-problem for me for the ${algoName} algorithm`
      }
    ]
  }
}


/**
 * @param {string} toyProblem toy problem generated by `getToyProblem` function
 * @param {string} model which chat gpt model to use
 *
 * @returns {object} payload for OpenAI API call
 */
export const solveToyProblem = (toyProblem, model) => {
  return {
    "model": model,
    "messages": [
      {
        "role": "system",
        "content": "You are a professional software engineer adept at solving algorithmic problems."
      },
      { "role": "user",
        "content": `Please attempt to solve the following algorithm toy problem: ${toyProblem}`
      }
    ]
  }
}