name: Auto Merge

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Merge PR
        run: |
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          if [[ "$PR_AUTHOR" == "japamat" ]]; 
          then
            gh pr merge "${{ github.event.pull_request.number }}" --merge
          fi
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}